### ISSUE TITLE
Unable to start my computer after installing this.

### ISSUE THREAD

**Issue by kz-n** [smartfrigde/GNU-EarthPol-Insider#1]
Hello, I have recently installed your copy of GNU-EarthPol-Insider and I beleive it had some kind of virus in it because whenever I try to run my pc it just opens a terminal and echoes "سمارتفريدج حاكم هذا العالم", How do I fix this?

**Comment by smartfrigde** [comment]
virus = feature

**Comment by kz-n** [comment]
This is unacceptable, I am suing you for the damages caused to my company, I have your software installed on 346 computers and we're facing MILLIONS of USD in debt, I am calling my lawyer and I will have the NSA tailing your ass in minutes.

**Comment by smartfrigde** [comment]
OMG AMDIANSDSA
DA PLS DONT SUE I PLS SAIDAS THIS IS OPEN SOURCEYOU CAN SUE THAT SJAFKASIHFOAS HAAHAHA GET DUCKED NOOB

**Comment by kz-n** [comment]
Fuck! I am screwed!
*cries in debt*
